package com.appsdeveloperblog.aws.photoapp.users;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import java.io.IOException;

public class Main {
    public static void main(String[] args) throws IOException {
        String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<Shipment ActualFreightCharge=\"0.00\" ActualShipmentDate=\"2023-05-12T12:33:25+00:00\" CarrierAccountNo=\"\" CarrierServiceCode=\"SHIPTOSTORE\" CarrierType=\"PARCEL\" Code=\"\" CommercialValue=\"0.00\" Currency=\"USD\" DeliveryCode=\"\" DeliveryTS=\"2023-05-12\" DestinationZone=\"\" DocumentType=\"0001\" DownLoadCount=\"0\" EnterpriseCode=\"AAP-MP\" ExpectedDeliveryDate=\"2023-05-12T11:32:43+00:00\" ExpectedShipmentDate=\"2023-05-12T11:32:43+00:00\" ExportTaxpayerID=\"\" FreightTerms=\"\" FromAddressKey=\"2022042715543814911669\" FromAppointment=\"2023-05-12\" HasOtherShipments=\"N\" HazardousMaterialFlag=\"N\" ITDate=\"2023-05-12\" NextAlertTs=\"1900-01-01T00:00:00+00:00\" NumOfCartons=\"1\" NumOfPallets=\"0\" OrderAvailableOnSystem=\"Y\" OriginZone=\"\" PackListType=\"\" PipelineKey=\"202207110952133213878\" SCAC=\"INSTORE\" SellerOrganizationCode=\"AAP-MP\" ShipDate=\"2023-05-12T12:33:25+00:00\" ShipMode=\"PARCEL\" ShipNode=\"963\" ShipVia=\"\" ShipmentClosedFlag=\"N\" ShipmentConfirmUpdatesDone=\"Y\" ShipmentContainerizedFlag=\"01\" ShipmentDeliverUpdatesDone=\"N\" ShipmentKey=\"20230512113244137520030\" ShipmentNo=\"100013351\" ShipmentPlannedFlag=\"N\" ShipmentType=\"ISPU\" StationId=\"\" StationType=\"\" Status=\"1400\" StatusDate=\"2023-05-12T12:33:25+00:00\" ToAddressKey=\"2022090808285156280106\" ToAppointment=\"2023-05-12\" TotalActualCharge=\"0.00\" TotalEstimatedCharge=\"0.00\" TotalVolume=\"18.90\" TotalVolumeUOM=\"CIN\" TotalWeight=\"0.09\" TotalWeightUOM=\"LBS\">\n" +
                "\t<ToAddress AddressLine1=\"\" AddressLine2=\"\" AddressLine3=\"\" AddressLine4=\"\" AddressLine5=\"\" AddressLine6=\"\" AlternateEmailID=\"\" Beeper=\"\" City=\"\" Company=\"\" Country=\"\" DayFaxNo=\"\" DayPhone=\"8789797987\" Department=\"\" EMailID=\"\" ErrorTxt=\"\" EveningFaxNo=\"\" EveningPhone=\"\" FirstName=\"Testing\" HttpUrl=\"\" JobTitle=\"\" LastName=\"Orders\" MiddleName=\"\" MobilePhone=\"\" OtherPhone=\"\" PersonID=\"\" PersonInfoKey=\"2022090808285156280106\" PreferredShipAddress=\"\" State=\"\" Suffix=\"\" Title=\"\" UseCount=\"0\" VerificationStatus=\"\" ZipCode=\"\"/>\n" +
                "\t<FromAddress AddressLine1=\"963 SAN PEDRO AVE\" AddressLine2=\"\" AddressLine3=\"\" AddressLine4=\"\" AddressLine5=\"\" AddressLine6=\"BEXAR\" AlternateEmailID=\"\" Beeper=\"\" City=\"SAN ANTONIO\" Company=\"\" Country=\"USA\" DayFaxNo=\"\" DayPhone=\"2134567890\" Department=\"\" EMailID=\"test@yopmail.com\" ErrorTxt=\"\" EveningFaxNo=\"\" EveningPhone=\"\" FirstName=\"\" HttpUrl=\"\" JobTitle=\"\" LastName=\"\" MiddleName=\"\" MobilePhone=\"\" OtherPhone=\"\" PersonID=\"\" PersonInfoKey=\"2022042715543814911669\" PreferredShipAddress=\"\" State=\"TX\" Suffix=\"\" Title=\"\" UseCount=\"0\" VerificationStatus=\"Verified\" ZipCode=\"78212\"/>\n" +
                "\t<Containers/>\n" +
                "\t<ShipmentLines>\n" +
                "\t\t<ShipmentLine ActualQuantity=\"1.00\" ChainedFromOrderHeaderKey=\"\" ChainedFromOrderLineKey=\"\" DocumentType=\"0001\" ItemDesc=\"&lt;table>&lt;tr>&lt;td>Intake Gasket Material:&lt;/td>&lt;td>Rubber&lt;/td>&lt;/tr>&lt;tr>&lt;td>Quantity Of Pieces:&lt;/td>&lt;td>1&lt;/td>&lt;/tr>&lt;/table>\" ItemID=\"20780504\" OrderHeaderKey=\"20230512112930137518569\" OrderLineKey=\"20230512112930137518570\" OrderNo=\"100123123123123038\" OrderReleaseKey=\"20230512113244137519998\" OverShipQuantity=\"0.00\" PrimeLineNo=\"1\" ProductClass=\"Good\" Quantity=\"1.00\" ReleaseNo=\"1\" Segment=\"\" SegmentType=\"\" ShipmentKey=\"20230512113244137520030\" ShipmentLineKey=\"20230512113244137520029\" ShipmentLineNo=\"1\" SubLineNo=\"1\" UnitOfMeasure=\"EACH\" isHistory=\"N\">\n" +
                "\t\t\t<OrderRelease OrderReleaseKey=\"20230512113244137519998\" ReleaseNo=\"1\" SalesOrderNo=\"100123123123123038\" ShipNode=\"963\">\n" +
                "\t\t\t\t<Extn ExtnHostOrderNo=\"3000000000\"/>\n" +
                "\t\t\t</OrderRelease>\n" +
                "\t\t\t<OrderLine ConditionVariable1=\"\" DeliveryMethod=\"PICK\" LineType=\"ISPU\" OrderHeaderKey=\"20230512112930137518569\" OrderLineKey=\"20230512112930137518570\" OrderedQty=\"1.00\" PrimeLineNo=\"1\" Purpose=\"\" SCAC=\"INSTORE\" ScacAndService=\"SHIPTOSTORE\" ShipNode=\"963\" SubLineNo=\"1\">\n" +
                "\t\t\t\t<Extn ExtnIsCoreSKU=\"N\" ExtnRollupNo=\"1\" ExtnShipModeId=\"P\" ExtnWarrantyDays=\"365\" ExtnWarrantyDescription=\"1 YR REPLACEMENT IF DEFECTIVE\"/>\n" +
                "\t\t\t\t<Item CostCurrency=\"\" CountryOfOrigin=\"\" CustomerItem=\"20780504\" CustomerItemDesc=\"brake pad\" ECCNNo=\"\" HarmonizedCode=\"\" ISBN=\"\" ItemDesc=\"&lt;table>&lt;tr>&lt;td>Intake Gasket Material:&lt;/td>&lt;td>Rubber&lt;/td>&lt;/tr>&lt;tr>&lt;td>Quantity Of Pieces:&lt;/td>&lt;td>1&lt;/td>&lt;/tr>&lt;/table>\" ItemID=\"20780504\" ItemShortDesc=\"Intake Manifold Gasket Set\" ItemWeight=\"0.09\" ItemWeightUOM=\"LBS\" ManufacturerItem=\"MS 97038\" ManufacturerItemDesc=\"\" ManufacturerName=\"Felpro\" NMFCClass=\"\" NMFCCode=\"\" NMFCDescription=\"\" ProductClass=\"Good\" ProductLine=\"\" ScheduleBCode=\"\" SupplierItem=\"\" SupplierItemDesc=\"\" TaxProductCode=\"89998\" UPCCode=\"\" UnitCost=\"0.00\" UnitOfMeasure=\"EACH\"/>\n" +
                "\t\t\t\t<ItemDetails CanUseAsServiceTool=\"N\" Createprogid=\"AAPMasterDataIntegrationServer\" Createts=\"2022-01-23T03:40:57+00:00\" Createuserid=\"AAPMasterDataIntegrationServer\" DisplayItemId=\"20780504\" GlobalItemID=\"\" InheritAttributesFromClassification=\"Y\" IsShippingCntr=\"N\" ItemGroupCode=\"PROD\" ItemID=\"20780504\" ItemKey=\"202201230340575610672\" Lockid=\"2\" MaxModifyTS=\"2022-11-10T15:30:15+00:00\" Modifyprogid=\"AAPMasterDataIntegrationServer\" Modifyts=\"2022-11-10T15:30:15+00:00\" Modifyuserid=\"AAPMasterDataIntegrationServer\" OrganizationCode=\"AAP-US\" UnitOfMeasure=\"EACH\">\n" +
                "\t\t\t\t\t<Extn ExtnMFRCode=\"FEL\" ExtnMFRPart=\"MS 97038\"/>\n" +
                "\t\t\t\t\t<PrimaryInformation AllowGiftWrap=\"N\" AssumeInfiniteInventory=\"N\" BundlePricingStrategy=\"PARENT\" CapacityPerOrderedQty=\"0.00\" CapacityQuantityStrategy=\"\" CapacityUOM=\"\" ComputedUnitCost=\"0.00\" CostCurrency=\"\" CountryOfOrigin=\"US\" CreditWOReceipt=\"N\" DefaultProductClass=\"Good\" Description=\"&lt;table>&lt;tr>&lt;td>Intake Gasket Material:&lt;/td>&lt;td>Rubber&lt;/td>&lt;/tr>&lt;tr>&lt;td>Quantity Of Pieces:&lt;/td>&lt;td>1&lt;/td>&lt;/tr>&lt;/table>\" ExtendedDescription=\"Fel-Pro gaskets offer 100% vehicle sealing with application-specific materials to give you sealing solutions with the performance and durability professionals trust&lt;br>&lt;br>&lt;b>Product Features:&lt;/b>&lt;ul>&lt;li type=disc>DESIGNED FOR IMPERFECT SEALING SURFACES -- Engineered and manufactured specifically for the repair environment to help seal imperfect sealing surfaces&lt;li type=disc>SEALING TECHNOLOGIES -- Exclusive sealing innovations and technologies with proprietary materials and unique design features to ensure a superior seal for your repair&lt;li type=disc>ENGINEERING EXPERTISE -- Parts are designed, reviewed, validated and approved by Fel-Pro engineers through rigorous research and development&lt;li type=disc>REAL-WORLD TESTED -- Parts are tested on-vehicle and validated to ensure optimal performance on the road&lt;li type=disc>EVERY PART FOR THE REPAIR -- Fel-Pro gasket sets include every part needed for the repair unless otherwise noted\" ExtendedDisplayDescription=\"Intake Manifold Gasket Set\" FixedCapacityQtyPerLine=\"0.00\" FixedPricingQtyPerLine=\"0.00\" ImageID=\"20780504_fel_ms97038_pri_detl.jpg\" ImageLocation=\"https://b2c-shop-qa6.test.advanceauto.cloud/wcsstore/CVWEB/staticproductimage/102/full/\" InvoiceBasedOnActuals=\"N\" InvolvesSegmentChange=\"N\" IsAirShippingAllowed=\"Y\" IsDeliveryAllowed=\"N\" IsEligibleForShippingDiscount=\"Y\" IsFreezerRequired=\"N\" IsHazmat=\"N\" IsParcelShippingAllowed=\"Y\" IsPickupAllowed=\"Y\" IsReturnService=\"N\" IsReturnable=\"Y\" IsShippingAllowed=\"Y\" IsStandaloneService=\"\" IsSubOnOrderAllowed=\"\" ItemType=\"\" KitCode=\"\" ManufacturerItem=\"MS 97038\" ManufacturerItemDesc=\"\" ManufacturerName=\"Felpro\" MasterCatalogID=\"\" MaxOrderQuantity=\"0.00\" MaxReturnWindow=\"0\" MinOrderQuantity=\"0.00\" MinimumCapacityQuantity=\"0.00\" NumSecondarySerials=\"0\" OrderingQuantityStrategy=\"ENT\" PricingQuantityConvFactor=\"0.00\" PricingQuantityStrategy=\"\" PricingUOM=\"\" PricingUOMStrategy=\"\" PrimaryEnterpriseCode=\"\" PrimarySupplier=\"\" ProductLine=\"\" RequiresProdAssociation=\"N\" ReturnWindow=\"0\" RunQuantity=\"0.00\" SerializedFlag=\"N\" ServiceTypeID=\"\" ShortDescription=\"Intake Manifold Gasket Set\" Status=\"3000\" TaxableFlag=\"N\" UnitCost=\"0.00\" UnitHeight=\"0.60\" UnitHeightUOM=\"IN\" UnitLength=\"9.00\" UnitLengthUOM=\"IN\" UnitWeight=\"0.09\" UnitWeightUOM=\"LBS\" UnitWidth=\"3.50\" UnitWidthUOM=\"IN\"/>\n" +
                "\t\t\t\t</ItemDetails>\n" +
                "\t\t\t\t<LineOverallTotals AdditionalLinePriceTotal=\"0.00\" Charges=\"0.00\" Discount=\"0.00\" ExtendedPrice=\"49.00\" LineCost=\"0.00\" LineTotal=\"53.59\" LineTotalWithoutTax=\"49.00\" ManualDiscountPercentage=\"0.00\" ManualOverridePercentage=\"0.00\" OptionPrice=\"0.00\" PercentProfitMargin=\"100.00\" PricingQty=\"1.00\" ShippingBaseCharge=\"0.00\" ShippingCharges=\"0.00\" ShippingDiscount=\"0.00\" ShippingTotal=\"0.00\" Tax=\"4.59\" UnitPrice=\"49.00\"/>\n" +
                "\t\t\t\t<LineCharges>\n" +
                "\t\t\t\t\t<LineCharge AmountFromAddnlLinePrices=\"0.00\" ChargeAmount=\"0.00\" ChargeCategory=\"CHARGE\" ChargeName=\"Price\" ChargeNameKey=\"\" ChargePerLine=\"0.00\" ChargePerUnit=\"0.00\" InvoicedChargeAmount=\"0.00\" InvoicedChargePerLine=\"0.00\" InvoicedChargePerUnit=\"0.00\" IsBillable=\"Y\" IsDiscount=\"N\" IsManual=\"Y\" IsShippingCharge=\"N\" Reference=\"Fee\" RemainingChargeAmount=\"0.00\" RemainingChargePerLine=\"0.00\" RemainingChargePerUnit=\"0.00\"/>\n" +
                "\t\t\t\t</LineCharges>\n" +
                "\t\t\t\t<LineTaxes>\n" +
                "\t\t\t\t\t<LineTax ChargeCategory=\"Price\" ChargeName=\"Price\" ChargeNameKey=\"\" InvoicedTax=\"0.00\" Reference_1=\"\" Reference_2=\"\" Reference_3=\"\" RemainingTax=\"4.59\" Tax=\"4.59\" TaxName=\"Price\" TaxPercentage=\"0.00\">\n" +
                "\t\t\t\t\t\t<Extn ExtnTaxAmount1=\"0.00\" ExtnTaxAmount2=\"0.00\" ExtnTaxAmount3=\"0.00\" ExtnTaxAmount4=\"0.00\" ExtnTaxAmount5=\"0.00\" ExtnTaxAmount6=\"0.00\" ExtnTaxAmount7=\"0.00\" ExtnTaxAmount8=\"0.00\"/>\n" +
                "\t\t\t\t\t</LineTax>\n" +
                "\t\t\t\t</LineTaxes>\n" +
                "\t\t\t</OrderLine>\n" +
                "\t\t\t<Order ActualPricingDate=\"2023-05-12T12:33:25+00:00\" AdjustmentInvoicePending=\"N\" AllAddressesVerified=\"N\" AuthorizationExpirationDate=\"2023-05-12T11:29:30+00:00\" BillToID=\"Walmart\" BillToKey=\"20210311173254554272\" CarrierAccountNo=\"\" CarrierServiceCode=\"\" ChainType=\"\" ChargeActualFreightFlag=\"N\" ComplimentaryGiftBoxQty=\"0\" CreatedAtNode=\"\" Createprogid=\"AAPWMCreateOrderIntegServer\" Createts=\"2023-05-12T11:29:30+00:00\" Createuserid=\"AAPWMCreateOrderIntegServer\" CustCustPONo=\"\" CustomerAge=\"0.00\" CustomerEMailID=\"8E69648701E9139F5DE@relay.walmart.com\" CustomerFirstName=\" \" CustomerLastName=\" \" CustomerPONo=\"123123123123123038\" CustomerPhoneNo=\" \" CustomerZipCode=\" \" DeliveryCode=\"\" Division=\"\" DoNotConsolidate=\"N\" DocumentType=\"0001\" DraftOrderFlag=\"N\" EnterpriseCode=\"AAP-MP\" EntryType=\"Walmart\" FreightTerms=\"\" HasDerivedChild=\"\" HasDerivedParent=\"\" HoldFlag=\"N\" HoldReasonCode=\"\" InternalApp=\"N\" InvoiceComplete=\"N\" Lockid=\"5\" Modifyprogid=\"AAPWMStoreNotificationsIntegServer\" Modifyts=\"2023-05-12T12:33:25+00:00\" Modifyuserid=\"AAPWMStoreNotificationsIntegServer\" NextAlertTs=\"2023-05-12T12:33:25+00:00\" NoOfAuthStrikes=\"0\" NotifyAfterShipmentFlag=\"N\" OrderComplete=\"N\" OrderDate=\"2023-05-12T10:49:31+00:00\" OrderHeaderKey=\"20230512112930137518569\" OrderName=\"\" OrderNo=\"100123123123123038\" OrderType=\"\" OriginalTax=\"0.00\" OriginalTotalAmount=\"121.18\" OtherCharges=\"0.00\" Override=\"N\" PaymentStatus=\"NOT_APPLICABLE\" PendingTransferIn=\"0.00\" PersonalizeCode=\"\" PriceOrder=\"\" PriceProgramName=\"\" PriorityCode=\"\" PriorityNumber=\"0\" PropagateCancellations=\"\" Purpose=\"\" ReserveInventoryFlag=\"\" ReturnByGiftRecipient=\"\" SCAC=\"\" SaleVoided=\"N\" SearchCriteria1=\"\" SearchCriteria2=\"\" SellerOrganizationCode=\"AAP-MP\" ShipToID=\"Walmart\" ShipToKey=\"2022090808285156280106\" SourceIPAddress=\" \" TaxExemptFlag=\"N\" TaxExemptionCertificate=\"\" TaxJurisdiction=\"\" TaxPayerId=\"\" TermsCode=\"\" TotalAdjustmentAmount=\"0.00\" isHistory=\"N\">\n" +
                "\t\t\t\t<Extn/>\n" +
                "\t\t\t\t<PaymentMethods/>\n" +
                "\t\t\t\t<PersonInfoBillTo AddressLine1=\"\" AddressLine2=\"\" AddressLine3=\"\" AddressLine4=\"\" AddressLine5=\"\" AddressLine6=\"\" AlternateEmailID=\"\" Beeper=\"\" City=\"\" Company=\"\" Country=\"US\" DayFaxNo=\"\" DayPhone=\"\" Department=\"\" EMailID=\"\" EveningFaxNo=\"\" EveningPhone=\"\" FirstName=\"\" JobTitle=\"\" LastName=\"\" MiddleName=\"\" MobilePhone=\"\" OtherPhone=\"\" PersonID=\"\" PersonInfoKey=\"20210311173254554272\" State=\"\" Suffix=\"\" Title=\"\" ZipCode=\"\"/>\n" +
                "\t\t\t\t<PersonInfoShipTo AddressLine1=\"\" AddressLine2=\"\" City=\"\" Company=\"\" Country=\"\" DayPhone=\"8789797987\" EMailID=\"\" FirstName=\"Testing\" LastName=\"Orders\" State=\"\" ZipCode=\"\"/>\n" +
                "\t\t\t\t<OrderLineRelationships/>\n" +
                "\t\t\t</Order>\n" +
                "\t\t</ShipmentLine>\n" +
                "\t</ShipmentLines>\n" +
                "\t<ShipmentCharges/>\n" +
                "</Shipment>";
//        String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
//                "<Shipment ActualShipmentDate=\"2022-08-25T16:48:05+00:00\" DocumentType=\"0001\" EnterpriseCode=\"AAP-MP\" SCAC=\"INSTORE\" SellerOrganizationCode=\"AAP-MP\" ShipDate=\"2022-08-25T16:48:05+00:00\" ShipNode=\"963\" ShipmentNo=\"100005100\" StatusDate=\"2022-08-25T16:48:06+00:00\">\n" +
//                "\t<FromAddress AddressLine1=\"963 SAN PEDRO AVE\" AddressLine2=\"\" City=\"SAN ANTONIO\" Company=\"\" Country=\"USA\" DayPhone=\"2134567890\" EMailID=\"test@yopmail.com\" FirstName=\"\" LastName=\"\" State=\"TX\" ZipCode=\"78212\"/>\n" +
//                "\t<ShipmentLines>\n" +
//                "\t\t<ShipmentLine ActualQuantity=\"1.00\" ItemID=\"3864014\" OrderHeaderKey=\"2022082508262351158635\" OrderLineKey=\"2022082508262351158636\" OrderNo=\"3333360\" OrderReleaseKey=\"2022082508315451160059\" PrimeLineNo=\"1\" Quantity=\"1.00\" ReleaseNo=\"1\" ShipmentLineKey=\"2022082508320051160074\" ShipmentLineNo=\"1\" SubLineNo=\"1\">\n" +
//                "\t\t\t<OrderRelease OrderReleaseKey=\"2022082508315451160059\" ReleaseNo=\"1\" SalesOrderNo=\"3333360\" ShipNode=\"963\"/>\n" +
//                "\t\t\t<OrderLine DeliveryMethod=\"PICK\" LineType=\"ISPU\" OrderHeaderKey=\"2022082508262351158635\" OrderLineKey=\"2022082508262351158636\" OrderedQty=\"1.00\" ShipNode=\"963\">\n" +
//                "\t\t\t\t<Extn ExtnIsCoreSKU=\"N\"/>\n" +
//                "\t\t\t\t<Item ItemDesc=\"&lt;table>&lt;tr>&lt;td>End 1 Gender:&lt;/td>&lt;td>Male&lt;/td>&lt;/tr>&lt;tr>&lt;td>End 1 Type:&lt;/td>&lt;td>Long Swivel O-ring&lt;/td>&lt;/tr>&lt;tr>&lt;td>End 2 Gender:&lt;/td>&lt;td>Male&lt;/td>&lt;/tr>&lt;tr>&lt;td\" ItemID=\"3864014\" ItemShortDesc=\"Pressure Hose Assembly\" ProductClass=\"Good\" UnitOfMeasure=\"EACH\"/>\n" +
//                "\t\t\t\t<ItemDetails ItemID=\"3864014\">\n" +
//                "\t\t\t\t\t<Extn ExtnAltImage=\"/18/full/3864014_qps_36629_alt1_pri_detl.jpg\" ExtnBrandCode=\"CQPSH\" ExtnFDOShipLTL=\"N\" ExtnFDOVendor=\"FDO_48271\" ExtnHasCoreSKU=\"N\" ExtnIsAgricultural=\"N\" ExtnIsCarTruck=\"N\" ExtnIsClearance=\"N\" ExtnIsFDOAble=\"Y\" ExtnIsFDOOnly=\"N\" ExtnIsMarine=\"N\" ExtnIsMotorcycleATV=\"N\" ExtnIsPWC=\"N\" ExtnIsRV=\"N\" ExtnIsRestricted=\"N\" ExtnIsSmallEngine=\"N\" ExtnIsSnowMobile=\"N\" ExtnLargeAltImage=\"/18/large/3864014_qps_36629_alt1_pri_larg.jpg\" ExtnLargeImage=\"/18/large/3864014_qps_36629_pri_larg.jpg\" ExtnMFRCode=\"QPS\" ExtnMFRPart=\"36629\" ExtnMiniImage=\"/18/mini/3864014_qps_36629_pri_mini.jpg\" ExtnProductType=\"1\" ExtnSMFRPart=\"36629\" ExtnThumbAltImage=\"/18/thumb/3864014_qps_36629_alt1_pri_thmb.jpg\" ExtnThumbnailImage=\"/18/thumb/3864014_qps_36629_pri_thmb.jpg\" ExtnWarCode=\"LIFEC\"/>\n" +
//                "\t\t\t\t</ItemDetails>\n" +
//                "\t\t\t\t<LineOverallTotals Charges=\"0.00\" Discount=\"0.00\" ExtendedPrice=\"10.99\" LineCost=\"0.00\" LineTotal=\"11.99\" LineTotalWithoutTax=\"10.99\" OptionPrice=\"0.00\" PricingQty=\"1.00\" ShippingCharges=\"0.00\" ShippingDiscount=\"0.00\" ShippingTotal=\"0.00\" Tax=\"1.00\" UnitPrice=\"10.99\"/>\n" +
//               // "\t\t\t\t<LineCharges/>\n" +
//                "\t\t\t\t<LineTaxes>\n" +
//                "\t\t\t\t\t<LineTax ChargeCategory=\"Price\" ChargeName=\"Price\" ChargeNameKey=\"\" InvoicedTax=\"0.00\" Reference_1=\"\" Reference_2=\"\" Reference_3=\"\" RemainingTax=\"1.00\" Tax=\"1.00\" TaxName=\"Price\" TaxPercentage=\"0.00\">\n" +
//                "\t\t\t\t\t\t<Extn ExtnTaxAmount1=\"0.00\" ExtnTaxAmount2=\"0.00\" ExtnTaxAmount3=\"0.00\" ExtnTaxAmount4=\"0.00\" ExtnTaxAmount5=\"0.00\" ExtnTaxAmount6=\"0.00\" ExtnTaxAmount7=\"0.00\" ExtnTaxAmount8=\"0.00\"/>\n" +
//                "\t\t\t\t\t</LineTax>\n" +
//                "\t\t\t\t</LineTaxes>\n" +
//                "\t\t\t</OrderLine>\n" +
//                "\t\t\t<Order CustomerPONo=\"30000000060\" DocumentType=\"0001\" EnterpriseCode=\"AAP-MP\" OrderDate=\"2022-12-24T17:39:10+00:00\" OrderHeaderKey=\"2022082508262351158635\" OrderNo=\"3333360\" SellerOrganizationCode=\"AAP-MP\">\n" +
//                "\t\t\t    \t<PersonInfoBillTo AddressLine1=\"\" AddressLine2=\"\" City=\"\" Company=\"\" Country=\"US\" DayPhone=\"\" EMailID=\"\" FirstName=\"\" LastName=\"\" State=\"\" ZipCode=\"\"/>\n" +
//                "\t\t\t\t<PersonInfoMarkFor AddressLine1=\"\" AddressLine2=\"\" City=\"\" Company=\"\" Country=\"\" DayPhone=\"2085550175\" EMailID=\"\" FirstName=\"firstName\" LastName=\"lastName\" State=\"\" ZipCode=\"\"/>\n" +
//                "\t\t\t\t<PersonInfoShipTo AddressLine1=\"\" AddressLine2=\"\" City=\"\" Company=\"\" Country=\"\" DayPhone=\"2085550175\" EMailID=\"\" FirstName=\"firstName\" LastName=\"lastName\" State=\"\" ZipCode=\"\"/>\n" +
//                "\t\t\t</Order>\n" +
//                "\t\t</ShipmentLine>\n" +
//                "\t</ShipmentLines>\n" +
//                "</Shipment>\n";

        XmlMapper xmlMapper = new XmlMapper();
        ObjectMapper jsonMapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);

        // Convert XML to JSON
        Shipment shipment = xmlMapper.readValue(xml, Shipment.class);

        String json = jsonMapper.writeValueAsString(shipment);

        // Print the JSON output
        System.out.println(json);
        System.out.println(shipment.toString());
    }
}
